# cmake file for Wiznet W5500-EVB-Pico2.
set(PICO_BOARD wiznet_w5500_evb_pico2)
set(MICROPY_PY_NETWORK_WIZNET5K W5500)
set(MICROPY_PY_LWIP 1)
set(MICROPY_FROZEN_MANIFEST ${MICROPY_BOARD_DIR}/manifest.py)
